import time
import board
import busio
from adafruit_pca9685 import PCA9685

# CODE GENERATED BY CHATGPT, HUMAN EDITED

i2c = busio.I2C(board.SCL, board.SDA)
pca = PCA9685(i2c)
pca.frequency = 50

def set_pulse_us(channel, pulse_us):
    period_us = 1000000 / 50  # 20,000 us period (???? what do you mean by this mr gpt)
    duty_cycle = int((pulse_us / period_us) * 0xFFFF)
    pca.channels[channel].duty_cycle = duty_cycle


neutral = 1600 
# look, i have no f***ing clue why 1600 is neutral. it should be 1500.
# but ive been at this for three days straight now, so i dont care. it works.

print("neutral")
set_pulse_us(0, neutral)
time.sleep(5)

print("Forward")
set_pulse_us(0, neutral + 300)
time.sleep(5)

print("Back to neutral")
set_pulse_us(0, neutral)
time.sleep(5)